### ISSUE TITLE
[implementation] Finalize “destriping” IBL preprocessing

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#1043]
The IBL's preprocessing pipeline includes the following steps which need to be ported and tested in SpikeInterface.
Reference white paper here: https://figshare.com/articles/online_resource/Spike_sorting_pipeline_for_the_International_Brain_Laboratory/19705522/3
 
- [x] Bad channel detection (#1070)
- [x] Bad channel interpolation/removal (#1025)
- [x] Phase shift (implemented [here](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/preprocessing/phase_shift.py))
- [x] Spatial `kfilt` filter (#1059)

### Additional comments

[JoeZiminski](https://github.com/JoeZiminski) from Cambridge University is working on this: https://github.com/SpikeInterface/spikeinterface/pull/1025

### ETA since in-progress

2-3 weeks

**Comment by JoeZiminski** [comment]
Thanks Alessio, bad channel interpolation and spatial filter are nearly done, just need to check a couple of things (aiming for PR today or Monday)

**Comment by alejoe91** [comment]
Sounds great! No rush :)
