### ISSUE TITLE
[feat-core]: implement sparse waveform extraction

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#1146]
- [x] Make new `ChannelSparsity` class (#1136)
- [x] Refactor existing sparsity handling with new object  (#1152)
- [x] Implement `save(..., sparsity)` function for `WaveformExtractor` (#1152)
- [x] Implement direct sparse waveform extraction  (#1152)
