### ISSUE TITLE
New naming for peak data type 

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#1409]
The current base_peak_dtype:
```
base_peak_dtype = [('sample_ind', 'int64'), ('channel_ind', 'int64'),
                   ('amplitude', 'float64'), ('segment_ind', 'int64')]
```
Do I remember correctly that we agreed to change this to have more explicit naming in a meeting but we did not follow through?

If that is the case, I can do it. 

What is the new naming?

- [x] * `sample_ind` -> `sample_index` #1556
- [x] * `channel_ind` -> `channel_index` #1534
- [x] * `amplitude` -> `ampitude`
- [x] * `segment_ind` -> `segment_index #1535
- [x] * `unit_id` -> `unit_index` [for spikevector in sorting objects] #1558
- [ ] * `cluster_ind` -> `cluster_index` #1571

**Comment by samuelgarcia** [comment]
Hi
I am agree for `ind` -> `index`
But I think we can keep `amplitudes` 

I prefer `peaks['ampitude']` over `peaks['peak_ampitude']`

I you go the modification can you also check the changes:
 * inside sorter module
 * in doc

**Comment by h-mayorquin** [comment]
Good point about the redundancy when referencing it from a peaks object!

**Comment by alejoe91** [comment]
`indices` should be the correct plural

**Comment by h-mayorquin** [comment]
@alejoe91 @samuelgarcia 
Note that neo uses `channel_indexes` (e.g. `_get_analogsignal_chunk`), are you guys fine with that discrepancy?

**Comment by samuelgarcia** [comment]
Copy paste from the web:

**Both “indexes” and “indices” are correct English plurals of the singular noun “index.” But there is a preference for indices outside North America because of solid adherence to Latin plurals.**

I guess Alessio sometimes feel a latin guy.

**Comment by h-mayorquin** [comment]
A Roman heritage. 

Outside of that it is easier to edit in bulk when the plurars are different from the singulars but on the other hand if you are looking for places where a term is used it might be a good idea that a simple search (no regular expression) would return both the terms (and that happens with the regular plural). I think that @pauladkisson pointed out something along those lines but can't recall.


No idea what's better. I think it is just better here to pick a standard and stick with it.

**Comment by pauladkisson** [comment]
Personally, I think I have a mild preference for 'indexes'.  'Indices' *feels* like the proper usage since it is much more common in mathematical/scientific language, but 'indexes' makes for easier code reading/writing since it is a regular plural.  I found this source to be helpful: [indexing - Proper terminology (Stack Overflow)](https://stackoverflow.com/questions/1378781/proper-terminology-should-i-say-indexes-or-indices)

**Comment by h-mayorquin** [comment]
Thanks for the link @pauladkisson . I actually had your mild preference till today when I went and check numpy and it seems that they do prefer indices:
https://numpy.org/doc/stable/reference/arrays.indexing.html

**Comment by alejoe91** [comment]
Thanks for the link @h-mayorquin 

Let's settle for `indices` then ;)
